version: '3.3'

services:
  bot:
    build: .
    container_name: bot
    restart: always
    depends_on:
      - redis
    ports:
      - "8020:8020"

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    command:
      - redis-server
