"""add vector strore id to User model

Revision ID: 409527a573af
Revises: 66066e377f67
Create Date: 2024-06-23 11:46:45.271661

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "409527a573af"
down_revision: Union[str, None] = "66066e377f67"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user", sa.Column("added_vector_store_id", sa.String(), nullable=True)
    )
    op.create_unique_constraint(None, "user", ["added_vector_store_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "user", type_="unique")
    op.drop_column("user", "added_vector_store_id")
    # ### end Alembic commands ###
